# Generated by Django 6.0.3 on 2026-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='type',
        ),
        migrations.RemoveField(
            model_name='performancerecord',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='performancerecord',
            name='score',
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('College', 'College'), ('University', 'University')], default='Primary School', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='attendance_rate_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='graduate_outcome_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='overall_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='student_satisfaction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
